version: '3.8'

name: dragons-and-dialogs
  
services:
  dnd-db:
    image: postgres:15.4-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dragons-and-dialogs
    ports:
      - 15001:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dnd-api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./src/api/.env
    ports:
      - 15002:80
    depends_on:
      - dnd-db

  dnd-web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 15003:80
    depends_on:
      - dnd-api
  
  dnd-pgadmin:
    image: dpage/pgadmin4:7.5
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 15004:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - dnd-db

volumes:
  postgres-data:
  pgadmin-data:
  
networks:
  default:
    name: dragons-and-dialogs